import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import { jobAPI } from '../services/api';
import Loading from '../components/ui/Loading';

export default function SavedJDs() {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(true);
    const [savedJDs, setSavedJDs] = useState([]);
    const [error, setError] = useState(null);

    useEffect(() => {
        fetchSavedJDs();
    }, []);

    const fetchSavedJDs = async () => {
        try {
            const userStr = localStorage.getItem('user');
            const user = userStr ? JSON.parse(userStr) : null;

            if (!user?._id) {
                navigate('/login');
                return;
            }

            const data = await jobAPI.getEmployerJDs(user._id);
            setSavedJDs(data);
        } catch (err) {
            console.error(err);
            setError("Failed to load saved JDs.");
        } finally {
            setLoading(false);
        }
    };

    const downloadPDF = (jd, versionIndex = null) => {
        const activeVersion = versionIndex !== null
            ? jd.versions.find(v => v.version === versionIndex)
            : jd.versions.find(v => v.version === jd.currentVersion);

        const text = activeVersion?.jdText;
        if (!text) return;

        const doc = new jsPDF();

        doc.setFontSize(20);
        doc.text(jd.input.jobTitle || 'Job Description', 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.text(`${jd.input.industry} | ${jd.input.experienceLevel}`, 105, 30, { align: 'center' });

        doc.setFontSize(10);
        const splitText = doc.splitTextToSize(text, 180);
        doc.text(splitText, 15, 45);

        doc.setFontSize(8);
        doc.text('Generated by Clarity Jobs', 105, 280, { align: 'center' });

        doc.save(`${jd.input.jobTitle.replace(/\s+/g, '_')}_JD.pdf`);
    };

    if (loading) return (
        <div className="bg-background-dark min-h-screen flex items-center justify-center text-ivory">
            <Loading message="Loading your vault..." />
        </div>
    );

    return (
        <div className="bg-background-dark min-h-screen font-sans text-ivory flex flex-col">
            {/* Header */}
            <header className="flex items-center justify-between shrink-0 border-b border-white/5 bg-background-dark/80 backdrop-blur-md px-8 py-4 sticky top-0 z-50">
                <div className="flex items-center gap-6">
                    <button
                        onClick={() => navigate('/jd-generator')}
                        className="flex items-center gap-3 group cursor-pointer hover:bg-white/5 pr-4 py-1.5 rounded-full transition-colors"
                    >
                        <div className="size-9 rounded-full bg-surface-dark flex items-center justify-center text-ivory-dim border border-white/10 group-hover:border-primary/50 group-hover:text-primary transition-all duration-300">
                            <span className="material-symbols-outlined text-xl group-hover:-translate-x-0.5 transition-transform">arrow_back</span>
                        </div>
                        <span className="text-xs font-bold tracking-widest uppercase text-ivory/80 font-mono group-hover:text-primary transition-colors">Back to Generator</span>
                    </button>
                    <h1 className="font-serif text-xl tracking-tight">Saved Job Descriptions</h1>
                </div>
            </header>

            <main className="flex-1 p-8 md:p-12 overflow-y-auto">
                <div className="max-w-7xl mx-auto space-y-6">

                    {error && (
                        <div className="bg-red-500/10 border border-red-500/20 text-red-200 p-4 rounded-sm text-sm font-mono">
                            {error}
                        </div>
                    )}

                    {savedJDs.length === 0 && !error ? (
                        <div className="flex flex-col items-center justify-center h-96 opacity-30">
                            <span className="material-symbols-outlined text-6xl mb-4">folder_open</span>
                            <p className="font-serif text-xl italic">No saved documents found.</p>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {savedJDs.map((jd) => (
                                <div key={jd._id} className="group bg-surface-dark border border-white/5 rounded-sm p-6 hover:border-primary/30 transition-all duration-300 shadow-lg hover:shadow-primary/5 flex flex-col h-[320px]">

                                    <div className="flex justify-between items-start mb-4">
                                        <div className="flex flex-col">
                                            <span className="font-mono text-[10px] uppercase tracking-widest text-primary/80 mb-1">{jd.input.industry}</span>
                                            <h3 className="font-serif text-2xl text-ivory group-hover:text-white transition-colors line-clamp-2">{jd.input.jobTitle}</h3>
                                        </div>
                                        <span className="bg-white/5 text-ivory-dim text-[10px] px-2 py-1 rounded-full font-mono">
                                            {new Date(jd.createdAt).toLocaleDateString()}
                                        </span>
                                    </div>

                                    <div className="flex-1 space-y-4">
                                        <div className="flex flex-wrap gap-2">
                                            <span className="text-xs border border-white/10 px-2 py-1 rounded-sm text-ivory-dim">{jd.input.experienceLevel}</span>
                                            <span className="text-xs border border-white/10 px-2 py-1 rounded-sm text-ivory-dim">{jd.input.location || 'Remote'}</span>
                                        </div>
                                        <p className="text-xs text-ivory-dim/60 line-clamp-3 font-light leading-relaxed">
                                            {jd.versions.find(v => v.version === jd.currentVersion)?.jdText.substring(0, 150)}...
                                        </p>
                                    </div>

                                    <div className="flex items-center justify-between pt-6 border-t border-white/5 mt-auto">
                                        <span className="text-[10px] font-mono text-ivory-dim/40">
                                            {jd.versions.length} Versions
                                        </span>
                                        <button
                                            onClick={() => downloadPDF(jd)}
                                            className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-primary hover:text-white transition-colors"
                                        >
                                            <span className="material-symbols-outlined text-lg">download</span>
                                            Download
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
}
